"""Fixture records for three agencies."""

SEED = [
    {"id": "cc-2026-0141", "tenant_id": "clark-county", "kind": "building permit",
     "title": "Residential addition, 1420 Alder Street",
     "body": "Application for a 480 square foot single-storey addition. Structural review complete. Awaiting final grading inspection and stormwater sign-off from the county engineer.",
     "status": "under review", "filed_on": "2026-06-14"},
    {"id": "cc-2026-0198", "tenant_id": "clark-county", "kind": "building permit",
     "title": "Commercial tenant improvement, 88 Mill Plain",
     "body": "Interior fit-out for a ground floor restaurant. Requires grease interceptor plan and fire suppression review. Health district referral issued.",
     "status": "approved", "filed_on": "2026-05-02"},
    {"id": "cc-2026-0233", "tenant_id": "clark-county", "kind": "variance",
     "title": "Setback variance request, Ridgefield parcel 88-1140",
     "body": "Applicant requests a four foot reduction to the rear setback to accommodate an accessory dwelling unit. Neighbour notification period closed with two comments received.",
     "status": "hearing scheduled", "filed_on": "2026-07-01"},
    {"id": "cc-2026-0250", "tenant_id": "clark-county", "kind": "code enforcement",
     "title": "Unpermitted deck construction, 77 Cedar Loop",
     "body": "Complaint received regarding a deck built without permit. Site visit confirmed construction. Notice of violation issued with thirty days to apply for retroactive permit.",
     "status": "open", "filed_on": "2026-07-22"},

    {"id": "rv-2026-0067", "tenant_id": "riverside", "kind": "capital project",
     "title": "Culvert replacement, Whitlock Creek crossing",
     "body": "Replacement of a failing corrugated metal culvert with a fish-passable box culvert. Requires hydraulic project approval and in-water work window compliance.",
     "status": "in construction", "filed_on": "2026-04-18"},
    {"id": "rv-2026-0092", "tenant_id": "riverside", "kind": "right of way",
     "title": "Utility trenching permit, Sycamore Avenue",
     "body": "Fibre conduit installation across 1,100 linear feet. Traffic control plan approved. Restoration bond posted and pavement moratorium waiver granted.",
     "status": "approved", "filed_on": "2026-06-30"},
    {"id": "rv-2026-0110", "tenant_id": "riverside", "kind": "capital project",
     "title": "Stormwater retention basin retrofit, Basin 4",
     "body": "Retrofit of an existing detention basin to add water quality treatment. Design at sixty percent. Easement acquisition from two adjacent parcels pending.",
     "status": "design", "filed_on": "2026-07-09"},

    {"id": "sw-2026-0012", "tenant_id": "statewide", "kind": "licence",
     "title": "Contractor licence renewal, general class A",
     "body": "Biennial renewal with bond verification and continuing education attestation. Insurance certificate on file and current.",
     "status": "approved", "filed_on": "2026-03-11"},
    {"id": "sw-2026-0044", "tenant_id": "statewide", "kind": "complaint",
     "title": "Consumer complaint, unfinished work",
     "body": "Complaint alleging abandonment of a residential project after partial payment. Licensee response received. Referred to mediation before formal disciplinary review.",
     "status": "under review", "filed_on": "2026-06-27"},
]
